# Generated by Django 3.0 on 2020-07-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('basic_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('picture_link', models.CharField(max_length=100)),
                ('headimg', models.FileField(upload_to='img/')),
                ('content', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('introduction', '简介'), ('value', '价值观'), ('value', '工作环境'), ('value', '人才培养方案')], default='introduction', max_length=50)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Excellent',
            fields=[
                ('excellence_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('sex', models.BooleanField()),
                ('position', models.CharField(max_length=50)),
                ('achievement', models.CharField(max_length=50)),
                ('picture_link', models.CharField(max_length=100)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('graduate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('award_record', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=100)),
                ('picture_link', models.CharField(max_length=100)),
                ('is_work', models.BooleanField()),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('honor_id', models.AutoField(primary_key=True, serialize=False)),
                ('honor_name', models.CharField(max_length=50)),
                ('honor_date', models.DateField()),
                ('honor_level', models.CharField(max_length=50)),
                ('honor_member', models.CharField(max_length=50)),
                ('honor_teacher', models.CharField(max_length=50)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('keep_hour', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
                ('object', models.CharField(max_length=50)),
                ('is_online', models.BooleanField()),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
