# Generated by Django 3.0 on 2020-07-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic',
            name='headimg',
        ),
        migrations.AlterField(
            model_name='basic',
            name='picture_link',
            field=models.FileField(upload_to='meida'),
        ),
    ]
